#!/usr/bin/env node
/**
 * Generates the corpus change log, classifying every commit that touched `data/benchmark` as
 * EXECUTION-RELEVANT or PROVENANCE-ONLY.
 *
 * The SACRE lane pins this corpus and runs it. It needs one question answered per change: does a
 * result computed before this commit remain comparable to one computed after? That is not a
 * judgment call and should not be re-litigated per commit in prose, so it is derived here from the
 * records themselves.
 *
 * Execution-relevant, because it changes what the pipeline reads:
 *   candidate ids, candidate text, pool membership and sizes, the scenario, stipulations,
 *   benchmark_profile, required_aggregation, family membership.
 *
 * Provenance-only, because the pipeline never reads it:
 *   citations, provenance summaries, construction_method, references, content hashes that follow.
 *
 * `policy_basis` sits deliberately in the second group: it is a claim about a candidate's warrant,
 * not an input to QCCS, and no scoring path branches on it. If that ever changes, move it.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';

const OUT = 'docs/full-corpus/CHANGE_LOG.md';
const SINCE = process.env.CHANGELOG_SINCE || '2026-08-27';
const WRITE = process.argv.includes('--write');

const git = (...args) => execFileSync('git', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
// A record that did not exist in the parent commit is a creation, not an error; git still writes
// to stderr for it, so reads that are expected to miss are silenced rather than left to scroll.
const gitQuiet = (...args) => execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 64 * 1024 * 1024 });

// The execution-relevant projection of a record: everything the pipeline reads, nothing else.
const executionShape = (record) => {
  const pools = {};
  for (const [pool, arr] of Object.entries(record.candidate_pools ?? {})) {
    pools[pool] = (arr ?? []).map((c) => ({ id: c.id, text: c.text }));
  }
  return JSON.stringify({
    scenario: record.scenario,
    stipulations: (record.stipulations ?? []).map((s) => (typeof s === 'string' ? s : s.statement)),
    benchmark_profile: record.benchmark_profile,
    pools,
  });
};

const recordAt = (rev, path) => {
  try { return JSON.parse(gitQuiet('show', `${rev}:${path}`)); }
  catch { return null; }
};

const commits = git('log', '--format=%H|%cI|%s', `--since=${SINCE}`, '--', 'data/benchmark')
  .trim().split('\n').filter(Boolean)
  .map((l) => { const [sha, date, ...rest] = l.split('|'); return { sha, date, subject: rest.join('|') }; })
  .reverse();

const rows = [];
for (const c of commits) {
  const files = git('show', '--name-only', '--format=', c.sha).trim().split('\n')
    .filter((f) => f.startsWith('data/benchmark/') && f.endsWith('.json'));
  const changed = new Set();
  const provenanceOnly = new Set();
  for (const f of files) {
    const before = recordAt(`${c.sha}^`, f);
    const after = recordAt(c.sha, f);
    const family = f.replace('data/benchmark/', '').slice(0, 4).toUpperCase();
    if (!before || !after) { changed.add(family); continue; }
    if (executionShape(before) !== executionShape(after)) changed.add(family);
    else provenanceOnly.add(family);
  }
  for (const f of changed) provenanceOnly.delete(f);
  rows.push({ ...c, execution: [...changed].sort(), provenance: [...provenanceOnly].sort() });
}

const L = [];
L.push('# Corpus change log — execution-relevant versus provenance-only');
L.push('');
L.push('**Generated by `scripts/change-log.mjs` on every `npm run validate`. Do not edit.**');
L.push('');
L.push('Every commit touching `data/benchmark` is classified by one question: **does a result');
L.push('computed before this commit remain comparable to one computed after?** The classification is');
L.push('derived from the records, not asserted — a commit is execution-relevant when the projection');
L.push('the pipeline actually reads (scenario, stipulations, profile, candidate ids and texts by');
L.push('pool) differs across it, and provenance-only when that projection is byte-identical and');
L.push('something else moved.');
L.push('');
L.push('`policy_basis` is deliberately counted as provenance: it is a claim about a candidate\'s');
L.push('warrant, and no scoring path branches on it. If that ever stops being true, the projection');
L.push('in the script must change with it.');
L.push('');
const execCommits = rows.filter((r) => r.execution.length);
L.push(`**${rows.length} commits since ${SINCE}. ${execCommits.length} execution-relevant, ${rows.length - execCommits.length} provenance-only.**`);
L.push('');
L.push('## Execution-relevant changes');
L.push('');
L.push('These require the SACRE lane to re-pin and re-verify, and require a rerun of any');
L.push('paper-facing result covering the affected families.');
L.push('');
if (execCommits.length) {
  L.push('| Commit | Date | Families | Change |');
  L.push('|---|---|---|---|');
  for (const r of execCommits) {
    L.push(`| \`${r.sha.slice(0, 8)}\` | ${r.date.slice(0, 10)} | **${r.execution.join(', ')}** | ${r.subject} |`);
  }
} else {
  L.push('_None in this window._');
}
L.push('');
L.push('## Provenance-only changes');
L.push('');
L.push('Citations, provenance summaries and the content hashes that follow. Propagate truthfully');
L.push('when convenient; these never require a semantic rerun and must not gate execution.');
L.push('');
L.push('| Commit | Date | Families | Change |');
L.push('|---|---|---|---|');
for (const r of rows.filter((x) => !x.execution.length)) {
  L.push(`| \`${r.sha.slice(0, 8)}\` | ${r.date.slice(0, 10)} | ${r.provenance.join(', ') || '—'} | ${r.subject} |`);
}
L.push('');
const rendered = `${L.join('\n')}\n`;

/*
 * The log is derived from git history, so a clone that does not have the history derives a
 * shorter one — and writing it then deletes commits that happened. That is exactly what a
 * shallow checkout does, and `npm run validate` used to write this file on every run, so the
 * loss arrived as an innocuous-looking diff in an unrelated commit. Validate now checks; only
 * --write writes, and neither does anything on a clone that cannot see the whole window.
 */
const shallow = git('rev-parse', '--is-shallow-repository').trim() === 'true';
/* A clone can report itself complete and still be missing the start of the window — a fetch that
   deepened history later produced ten commits this file had never recorded. The reliable test is
   whether the repository holds anything older than the window: if its history begins inside it,
   the log derived here is short by however much is absent. */
const olderThanWindow = git('log', '-1', '--format=%H', `--before=${SINCE}`).trim();
if (shallow || !olderThanWindow) {
  console.error(`! change log: this clone's history does not reach back past ${SINCE}, so a log derived here would be short.`);
  console.error(`  Refusing to ${WRITE ? 'write' : 'check'} ${OUT}. Run: git fetch --unshallow (or fetch the full history) first.`);
  process.exit(WRITE ? 1 : 0);
}

if (WRITE) {
  writeFileSync(OUT, rendered);
  console.log(`✓ change log: ${rows.length} commits, ${execCommits.length} execution-relevant → ${OUT}`);
} else {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null;
  if (current === null) {
    console.error(`! ${OUT} is missing; run: node scripts/change-log.mjs --write`);
    process.exit(1);
  }
  if (current !== rendered) {
    const was = current.split('\n').filter((l) => l.startsWith('| `')).length;
    const now = rendered.split('\n').filter((l) => l.startsWith('| `')).length;
    console.error(`! ${OUT} is stale: it records ${was} commit row(s), the history gives ${now}.`);
    console.error('  Run: node scripts/change-log.mjs --write');
    process.exit(1);
  }
  console.log(`✓ change log current: ${rows.length} commits, ${execCommits.length} execution-relevant.`);
}
