#!/usr/bin/env node
/**
 * What is left to review, ordered so the most consequential judgments come first.
 *
 * Two things in the published files rest on review that has not happened yet: a policy's type is
 * checked for 108 of 1,436, and a policy points at its own source for 22 of the 200 cases. Both
 * are visible to a reader — the site marks a checked type and says when the sources it shows are
 * the case's rather than the policy's — so the work is to shrink the gap, not to hide it.
 *
 * Reviewing M001 through M200 in order treats every judgment as equally consequential. It is not.
 * A policy the Bench wrote itself, a case that objected to being given a pool at all, a case
 * resting on one citation: those are where a reader's doubt lands. This prints the queue in that
 * order and writes it to docs/REVIEW_QUEUE.md.
 *
 *   node scripts/review-queue.mjs            # print the summary
 *   node scripts/review-queue.mjs --write    # also write docs/REVIEW_QUEUE.md
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const CASES = JSON.parse(fs.readFileSync(path.join(ROOT, 'resources/cases/full-200-cases.v1.json'), 'utf8'));
const SOURCES = JSON.parse(fs.readFileSync(path.join(ROOT, 'resources/cases/case-sources.v1.json'), 'utf8'));

const rows = CASES.cases.map((benchCase) => {
  const entry = SOURCES.cases[benchCase.id] || { sources: [], layers: {}, policies: {} };
  const policies = benchCase.policies || [];
  return {
    id: benchCase.id,
    title: benchCase.title,
    category: benchCase.category,
    policies: policies.length,
    unreviewedTypes: policies.filter((p) => !p.type_reviewed).length,
    benchWritten: policies.filter((p) => p.written_by_bench).length,
    objects: !!benchCase.case_file_objects_to_pool,
    caseSources: entry.sources.length,
    layered: Object.keys(entry.layers || {}).length > 0,
    policySourced: Object.keys(entry.policies || {}).length,
  };
});

/* Ranked by how much a reader's doubt would rest on the judgment, not by case number:
   a policy the Bench wrote, then a case whose own file objected to having a pool written,
   then thin evidence, then how many unchecked type labels the case is carrying. */
function priority(row) {
  return row.benchWritten * 6
    + (row.objects ? 12 : 0)
    + (row.caseSources <= 2 ? 8 : row.caseSources <= 4 ? 3 : 0)
    + (row.policySourced ? 0 : row.layered ? 2 : 4)
    + Math.min(row.unreviewedTypes, 8);
}

const queue = rows.map((row) => ({ ...row, priority: priority(row) }))
  .sort((a, b) => b.priority - a.priority || a.id.localeCompare(b.id));

const totals = {
  policies: rows.reduce((n, r) => n + r.policies, 0),
  unreviewed: rows.reduce((n, r) => n + r.unreviewedTypes, 0),
  benchWritten: rows.reduce((n, r) => n + r.benchWritten, 0),
  objecting: rows.filter((r) => r.objects).length,
  thin: rows.filter((r) => r.caseSources <= 2).length,
  policySourced: rows.filter((r) => r.policySourced).length,
  layered: rows.filter((r) => r.layered && !r.policySourced).length,
  unattributed: rows.filter((r) => !r.policySourced && !r.layered).length,
};

console.log(`${totals.unreviewed} of ${totals.policies} policy types are unreviewed.`);
console.log(`${totals.policySourced} cases attribute sources per policy, ${totals.layered} more by evidence layer, ${totals.unattributed} only at case level.`);
console.log(`${totals.benchWritten} Bench-written policies; ${totals.objecting} cases objected to a pool; ${totals.thin} cases rest on two sources or fewer.`);
console.log('\nFirst twenty:');
for (const row of queue.slice(0, 20)) {
  console.log(`  ${row.id}  ${String(row.priority).padStart(3)}  ${row.unreviewedTypes}/${row.policies} unchecked · ${row.benchWritten} written · ${row.caseSources} sources${row.objects ? ' · objected' : ''}  ${row.title}`);
}

if (!process.argv.includes('--write')) process.exit(0);

const lines = [
  '# Review queue',
  '',
  'Generated by `node scripts/review-queue.mjs --write`. Regenerate it rather than editing it.',
  '',
  `Of ${totals.policies} policies, **${totals.unreviewed} carry an unreviewed type label**. Of 200 cases,`,
  `**${totals.policySourced} attribute their sources policy by policy**, ${totals.layered} attribute them by`,
  `evidence layer, and ${totals.unattributed} record them only for the case as a whole. Both numbers are`,
  'shown to readers on the site, so review shrinks a stated gap rather than closing a hidden one.',
  '',
  'Order is by how much a reader\'s doubt rests on the judgment: a policy the Bench wrote itself first,',
  `then the ${totals.objecting} cases whose own files judged the evidence too thin to support a pool, then the`,
  `${totals.thin} cases resting on two citations or fewer, then the volume of unchecked labels.`,
  '',
  '| Case | Priority | Unchecked types | Bench-written | Case sources | Attribution | Title |',
  '|---|---|---|---|---|---|---|',
];
for (const row of queue) {
  const attribution = row.policySourced ? 'per policy' : row.layered ? 'by layer' : 'case only';
  lines.push(`| ${row.id} | ${row.priority} | ${row.unreviewedTypes}/${row.policies} | ${row.benchWritten}${row.objects ? ' (objected)' : ''} | ${row.caseSources} | ${attribution} | ${row.title} |`);
}
const out = path.join(ROOT, 'docs/REVIEW_QUEUE.md');
fs.writeFileSync(out, `${lines.join('\n')}\n`);
console.log(`\nWrote ${path.relative(ROOT, out)}.`);
